<?php

/**
 * @file
 * This file alters the team member (user profile) output
 * Publications and subprojects are added
 * 
 */

/**
 * Implements hook_user_view
 */
function poli_team_user_view($account, $view_mode, $langcode) {
  // define the uid
  $uid = $account->uid;

  // add "subprojects_per_user" view to the account
  $subprojects_per_user = views_embed_view('subprojects_per_user', 'block', $uid);
  $account->content['subprojects'] = array(
    '#markup' => $subprojects_per_user,
    '#prefix' => '<h2>Subprojects</h2>',
    '#weight' => 100,
  );
  
  $firstname_field = field_get_items('user', $account, 'field_user_firstname');
  $firstname = $firstname_field[0]['value'];
  
  $lastname_field = field_get_items('user', $account, 'field_user_lastname');
  $lastname = $lastname_field[0]['value'];
  
  $name = sprintf('%s %s', $firstname, $lastname);
  
  drupal_set_title($name);
  
}

/**
 * Implements hook_preprocess_page
 */
function poli_team_preprocess_page($variables, $hook) {
/*
  d
  unset($variables['title']);
*/
/*
  print "<pre>";
  print_r($variables);
  print "</pre>";
*/
}