<?php

/**
 * @file
 * This file alters the team member (user profile) output
 * Publications and subprojects are added
 * 
 */

/**
 * Implements hook_user_view
 */
function poli_team_user_view($account, $view_mode, $langcode) {
  $uid = $account->uid;

  $number_of_subprojects = views_get_view_result('subprojects', 'user', $uid);

  if (count($number_of_subprojects)) {
	  $account->content['subprojects'] = array(
	    '#markup' => views_embed_view('subprojects', 'user', $uid),
	    '#prefix' => '<div class="subprojects"><h2>Subprojects</h2>',
	    '#suffix' => '</div>',
	    '#weight' => 100,
	  );
  }
  
  $publications_block = module_invoke('poli_publications', 'block_view', 'poli_publications_per_user');
  
  $account->content['publications'] = array(
    '#markup' => $publications_block['content'],
    '#prefix' => '<div class="publications"><h2>Publications</h2>',
    '#suffix' => '</div>',
    '#weight' => 200,
  );
  
  $firstname_field = field_get_items('user', $account, 'field_user_firstname');
  $firstname = $firstname_field[0]['value'];
  
  $lastname_field = field_get_items('user', $account, 'field_user_lastname');
  $lastname = $lastname_field[0]['value'];
  
  $name = sprintf('%s %s', $firstname, $lastname);
  
  drupal_set_title($name);
  
}