<?php

/**
 * @file
 * This module processes views output for subprojects overview
 */

/**
 * Implements hook_preprocess_page
 */
function poli_subprojects_preprocess_node(&$variables, $hook) {
  if ($variables['type'] == 'research_theme' && $variables['view_mode'] != 'teaser') {
    $nid = $variables['nid'];
    $number_of_subprojects = views_get_view_result('subprojects', 'research_theme', $nid);
    if (count($number_of_subprojects)) {
	    $variables['content']['subprojects'] = array(
	      '#markup' => views_embed_view('subprojects', 'research_theme', $nid),
	      '#weight' => 100,
	      '#prefix' => '<div class="subprojects"><h2>Subprojects</h2>',
	      '#suffix' => '</div>',
	    );
    }
	}
}